---

image:
  name: pandoc/core:latest-alpine
  entrypoint: ["/bin/sh", "-c"]

pages:
  stage: deploy
  script:
    - apk update
    - apk add wget make git graphviz py3-pip texlive-full texmf-dist texlive-xetex librsvg fontconfig
    - mkdir -p venv
    - python3 -m venv venv
    - source venv/bin/activate
    - pip install pandoc-include
    - mkdir -p $HOME/.fonts
    - wget https://www.gust.org.pl/projects/e-foundry/tex-gyre/pagella/qpl2_501otf.zip
    - unzip qpl2_501otf.zip
    - mv qpl2_501otf/*.otf $HOME/.fonts
    - fc-cache -f $HOME/.fonts
    - git submodule update --init
    - make WEB=1
  artifacts:
    paths:
      - public
  only:
    - master
