---

image:
  name: pandoc/core:latest-alpine
  entrypoint: ["/bin/sh", "-c"]

pages:
  stage: deploy
  script:
    - apk update
    - apk add wget make git graphviz py3-pip
    - pip install pandoc-include
    - git submodule update --init --recursive
    - make
  artifacts:
    paths:
      - public
  only:
    - master
