---

image:
  name: pandoc/alpine:latest
  entrypoint: ["/bin/sh", "-c"]

pages:
  stage: deploy
  script:
    - apk update
    - apk add wget make git graphviz
    - git submodule update --init --recursive
    - make
  artifacts:
    paths:
      - public
  only:
    - master
